### ISSUE TITLE
Use OSM old_name tag for name matching

### ISSUE THREAD

**Issue by b1tw153** [ZeLonewolf/wikidata-qa#14]
Similar to #3, check the old_name tag in OSM when matching against the CDP list.

For example, Yokuts Valley ([OSM](https://www.openstreetmap.org/relation/14569865), [Wikidata](https://www.wikidata.org/wiki/Q2141628)) was previously known as Squaw Valley. This name is present in the old_name tag in OSM and the previous values of the name (P2561) property in Wikidata.

However, the current report flags Yokuts Valley because "OSM boundary=census Yokuts Valley is not on the census bureau [list](https://tigerweb.geo.census.gov/tigerwebmain/Files/tab20/tigerweb_tab20_cdp_2020_ca.html) of CDPs". The Census Bureau list still has the old name of Squaw Valley and does not have the current name of Yokuts Valley.

**Comment by ZeLonewolf** [comment]
I have run into this issue also in other states.  However, what is our source for the CDP name changing?  Doesn't the census bureau control what the name of the CDP is?

**Comment by b1tw153** [comment]
I guess this particular case is going to be difficult. GNIS has Yokuts Valley as the [Populated Place ](https://edits.nationalmap.gov/apps/gaz-domestic/public/search/names/1659853) but also the corresponding [Squaw Valley Census Designated Place](https://edits.nationalmap.gov/apps/gaz-domestic/public/search/names/2408799).

This particular renaming has been [contentious](https://www.sfgate.com/centralcoast/article/fresno-yokuts-valley-measure-18977592.php), but I'm not sure that relying on the Census Bureau to restore the Squaw Valley name would be right in this case.

**Comment by ZeLonewolf** [comment]
Completed in 82a450a
