### ISSUE TITLE
404 error for state names with space in name 

### ISSUE THREAD

**Issue by wireguy** [ZeLonewolf/wikidata-qa#19]
test case, New Jersey getting 404 error
`https://zelonewolf.github.io/wikidata-qa/New%20Jersey_citiesAndTowns.html`

https://github.com/ZeLonewolf/wikidata-qa/blob/b9d791ddf67b5d33a218f158f47284db6e772feb/wikidata_boundary_check.js#L453C151-L453C164

`${state.name}`
should be something like?
`${state.name.replace(" ", "_")}`

**Comment by ZeLonewolf** [comment]
Yup good catch. Should be an underscore

**Comment by wireguy** [comment]
nj's list shows as https://zelonewolf.github.io/wikidata-qa/undefined_citiesAndTowns.html

**Comment by ZeLonewolf** [comment]
Should be resolved now
