### ISSUE TITLE
Respect OSM alt_name tag for name matching

### ISSUE THREAD

**Issue by wireguy** [ZeLonewolf/wikidata-qa#3]
Check the OSM alt_name tag for possible match with wikidata entry 

example:
[Amberley Ohio](https://en.wikipedia.org/wiki/Amberley%2C_Ohio) is a village in Ohio
It seems to locally go by the name Amberley Village
[wikidata ](https://www.wikidata.org/wiki/Q2673467) and [wikipedia](https://en.wikipedia.org/wiki/Amberley%2C_Ohi) use Amberley
wikidata lists several aka's, but that seems like more work.

[Amberley Village](https://www.openstreetmap.org/relation/182216) in OSM has `alt_name=Amberley`

another example:
[The Village of Indian Hill](https://www.openstreetmap.org/relation/182244) in OSM has `alt_name=Indian Hill`

**Comment by wireguy** [comment]
can alt_name be used to match against census/CDP info?

Noticed that in NJ, there is a LeisureTowne, that has an alt_name of Leisuretowne (T in towne is lowercase), but gets:
`OSM boundary=census LeisureTowne is not on the census bureau [list](https://tigerweb.geo.census.gov/tigerwebmain/Files/tab20/tigerweb_tab20_cdp_2020_nj.html) of CDPs`

**Comment by ZeLonewolf** [comment]
Right now, alt_name is used for matching, but all matching is case-sensitive.

**Comment by wireguy** [comment]
let index = unfoundCDPs.findIndex(item => item === row['name']);

should/could that check also use alt_name

Found a non case example,  Hillsborough Township vs Hillsborough (I just added the alt_name=Hillsborough).
CDP is called Hillsborough CDP,  Postal address and formal name are Hillsborough Township
Everyone just calls it Hillsborough

**Comment by ZeLonewolf** [comment]
We are now matching `name` against all labels in wikidata.  If something in a `name` tag is missing from wikidata's main label or aliases, it should get added to the alias list.

**Comment by ZeLonewolf** [comment]
Completed in 82a450a
