### ISSUE TITLE
Redundant Flag on Wikidata P1448 (official name)?

### ISSUE THREAD

**Issue by dknelson9876** [ZeLonewolf/wikidata-qa#44]
The results for Utah currently has 153 hits for "P1448 exists in Wikidata but no official_name in OSM". A random sampling of wikidata pages that I checked had the same value for the name and official name. I'm unfamiliar with wikidata expectations, should it have duplicate values like this?

Either way, in OSM `official_name` is only for when it's value is different from `name`. Could you add a check so that this flag is only raised when `official_name` would be necessary?

**Comment by ZeLonewolf** [comment]
That's a good idea, thanks. The genesis of this finding is from New York state where formal names are used in the name tag as disambiguators.

**Comment by ZeLonewolf** [comment]
In this case, after more research, I found that the official name properties on the wikidata side should never have been set.  Someone added this entry in bulk from the name tag.  I'm in the process of reverting this from wikidata.  In the case of true official names (usually something like "City of XXX"), an `official_name` tag on the OSM tag would still be appropriate.
