### ISSUE TITLE
Inactive Workflow

### ISSUE THREAD

**Issue by tylerfilla** [ZeLonewolf/wikidata-qa#6]
Very cool! It fell asleep, though 😴

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

**Comment by ZeLonewolf** [comment]
Thanks.  I have to manually press the button to re-enable that if there aren't any code changes after two months. It's running now but maybe I can get around this with a self-hosted runner.

**Comment by tylerfilla** [comment]
Do you think a separate scheduled workflow can keep it alive by making a periodic commit (maybe on another branch)?

**Comment by ZeLonewolf** [comment]
That would be an interesting hack, but I would prefer not to do things that probably violate GitHub's TOS.

**Comment by tylerfilla** [comment]
Fair enough. I'm going to close this issue now.
